### PR TITLE
(+semver: feature) EN-8610: Add product ID for new Prolific device

### PR DESCRIPTION
**Pull request by thzinc**

### CODE REVIEW

**Review by BorisGanov-GMV — APPROVED** [review]
Is that the new dock vendor Id?

LGTM

**Comment by thzinc** [comment]
@BorisGanov-GMV, yep. Leif confirmed by using an app on the Getac to inspect the USB device tree while connected to each dock. Our latest batch of docks use a Prolific USB-to-serial chip that identifies itself as USB product ID `23A3` instead of `2303`. This appears to be an atypical product ID for this device. It's not mentioned specifically on [Prolific's own list of USB-to-serial chips][prolific]. I only found a mention of the `23A3` on a [Linux forum][mention] that mentioned another company: ATEN. ATEN appear to use Prolific chips in their products and possibly have updated product ID in the firmware on the chip.

[prolific]: http://www.prolific.com.tw/US/ShowProduct.aspx?pcid=41
[mention]: http://linux-hardware.org/index.php?id=usb:067b-23a3

**Review by BorisGanov-GMV — APPROVED** [review]

**Review by dkaminski — APPROVED** [review]
LGTM

**Comment by BorisGanov-GMV** [comment]
Merging...

**Pull request merged**
